namespace RecuBackend.Api.Dtos;

public sealed record CharacterResponse(
    Guid Id,
    Guid CampaignId,
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    int Initiative,
    int SpeedFeet,
    string Size,
    bool IsNpc,
    DateTime CreatedAtUtc);

public sealed record CreateCharacterRequest(
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    int Initiative,
    int SpeedFeet,
    string Size,
    bool IsNpc);

public sealed record UpdateCharacterRequest(
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    int Initiative,
    int SpeedFeet,
    string Size,
    bool IsNpc);
