namespace RecuBackend.Api.Dtos;

public sealed record CharacterResponse(
    Guid Id,
    Guid CampaignId,
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int CurrentHitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    string Alignment,
    string Background,
    string Languages,
    IReadOnlyList<string> SkillProficiencies,
    bool IsNpc,
    DateTime CreatedAtUtc);

public sealed record CreateCharacterRequest(
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int CurrentHitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    string Alignment,
    string Background,
    string Languages,
    IReadOnlyList<string>? SkillProficiencies,
    bool IsNpc);

public sealed record UpdateCharacterRequest(
    string Name,
    string Race,
    string CharacterClass,
    int Level,
    int ArmorClass,
    int HitPoints,
    int CurrentHitPoints,
    int ProficiencyBonus,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    string Alignment,
    string Background,
    string Languages,
    IReadOnlyList<string>? SkillProficiencies,
    bool IsNpc);
